export const allCurrencies = [
  { code: "AED", name: "UAE Dirham (AED)" },
  { code: "AFN", name: "Afghan Afghani (AFN)" },
  { code: "ALL", name: "Albanian Lek (ALL)" },
  { code: "AMD", name: "Armenian Dram (AMD)" },
  { code: "ANG", name: "Netherlands Antillian Guilder (ANG)" },
  { code: "AOA", name: "Angolan Kwanza (AOA)" },
  { code: "ARS", name: "Argentine Peso (ARS)" },
  { code: "AUD", name: "Australian Dollar (AUD)" },
  { code: "AWG", name: "Aruban Florin (AWG)" },
  { code: "AZN", name: "Azerbaijani Manat (AZN)" },
  { code: "BAM", name: "Bosnia and Herzegovina Mark (BAM)" },
  { code: "BBD", name: "Barbados Dollar (BBD)" },
  { code: "BDT", name: "Bangladeshi Taka (BDT)" },
  { code: "BGN", name: "Bulgarian Lev (BGN)" },
  { code: "BHD", name: "Bahraini Dinar (BHD)" },
  { code: "BIF", name: "Burundian Franc (BIF)" },
  { code: "BMD", name: "Bermudian Dollar (BMD)" },
  { code: "BND", name: "Brunei Dollar (BND)" },
  { code: "BOB", name: "Bolivian Boliviano (BOB)" },
  { code: "BRL", name: "Brazilian Real (BRL)" },
  { code: "BSD", name: "Bahamian Dollar (BSD)" },
  { code: "BTN", name: "Bhutanese Ngultrum (BTN)" },
  { code: "BWP", name: "Botswana Pula (BWP)" },
  { code: "BYN", name: "Belarusian Ruble (BYN)" },
  { code: "BZD", name: "Belize Dollar (BZD)" },
  { code: "CAD", name: "Canadian Dollar (CAD)" },
  { code: "CDF", name: "Congolese Franc (CDF)" },
  { code: "CHF", name: "Swiss Franc (CHF)" },
  { code: "CLP", name: "Chilean Peso (CLP)" },
  { code: "CNY", name: "Chinese Renminbi (CNY)" },
  { code: "COP", name: "Colombian Peso (COP)" },
  { code: "CRC", name: "Costa Rican Colon (CRC)" },
  { code: "CUP", name: "Cuban Peso (CUP)" },
  { code: "CVE", name: "Cape Verdean Escudo (CVE)" },
  { code: "CZK", name: "Czech Koruna (CZK)" },
  { code: "DJF", name: "Djiboutian Franc (DJF)" },
  { code: "DKK", name: "Danish Krone (DKK)" },
  { code: "DOP", name: "Dominican Peso (DOP)" },
  { code: "DZD", name: "Algerian Dinar (DZD)" },
  { code: "EGP", name: "Egyptian Pound (EGP)" },
  { code: "ERN", name: "Eritrean Nakfa (ERN)" },
  { code: "ETB", name: "Ethiopian Birr (ETB)" },
  { code: "EUR", name: "Euro (EUR)" },
  { code: "FJD", name: "Fijian Dollar (FJD)" },
  { code: "FKP", name: "Falkland Islands Pound (FKP)" },
  { code: "FOK", name: "Faroese Króna (FOK)" },
  { code: "GBP", name: "British Pound Sterling (GBP)" },
  { code: "GEL", name: "Georgian Lari (GEL)" },
  { code: "GGP", name: "Guernsey Pound (GGP)" },
  { code: "GHS", name: "Ghanaian Cedi (GHS)" },
  { code: "GIP", name: "Gibraltar Pound (GIP)" },
  { code: "GMD", name: "Gambian Dalasi (GMD)" },
  { code: "GNF", name: "Guinean Franc (GNF)" },
  { code: "GTQ", name: "Guatemalan Quetzal (GTQ)" },
  { code: "GYD", name: "Guyanese Dollar (GYD)" },
  { code: "HKD", name: "Hong Kong Dollar (HKD)" },
  { code: "HNL", name: "Honduran Lempira (HNL)" },
  { code: "HRK", name: "Croatian Kuna (HRK)" },
  { code: "HTG", name: "Haitian Gourde (HTG)" },
  { code: "HUF", name: "Hungarian Forint (HUF)" },
  { code: "INR", name: "Indian Rupee (INR)" },
  { code: "IDR", name: "Indonesian Rupiah (IDR)" },
  { code: "ILS", name: "Israeli New Shekel (ILS)" },
  { code: "IMP", name: "Isle of Man Pound (IMP)" },
  { code: "IQD", name: "Iraqi Dinar (IQD)" },
  { code: "IRR", name: "Iranian Rial (IRR)" },
  { code: "ISK", name: "Icelandic Króna (ISK)" },
  { code: "JEP", name: "Jersey Pound (JEP)" },
  { code: "JMD", name: "Jamaican Dollar (JMD)" },
  { code: "JOD", name: "Jordanian Dinar (JOD)" },
  { code: "JPY", name: "Japanese Yen (JPY)" },
  { code: "KES", name: "Kenyan Shilling (KES)" },
  { code: "KGS", name: "Kyrgyzstani Som (KGS)" },
  { code: "KHR", name: "Cambodian Riel (KHR)" },
  { code: "KID", name: "Kiribati Dollar (KID)" },
  { code: "KMF", name: "Comorian Franc (KMF)" },
  { code: "KRW", name: "South Korean Won (KRW)" },
  { code: "KWD", name: "Kuwaiti Dinar (KWD)" },
  { code: "KYD", name: "Cayman Islands Dollar (KYD)" },
  { code: "KZT", name: "Kazakhstani Tenge (KZT)" },
  { code: "LAK", name: "Lao Kip (LAK)" },
  { code: "LBP", name: "Lebanese Pound (LBP)" },
  { code: "LKR", name: "Sri Lankan Rupee (LKR)" },
  { code: "LRD", name: "Liberian Dollar (LRD)" },
  { code: "LSL", name: "Lesotho Loti (LSL)" },
  { code: "LYD", name: "Libyan Dinar (LYD)" },
  { code: "MAD", name: "Moroccan Dirham (MAD)" },
  { code: "MDL", name: "Moldovan Leu (MDL)" },
  { code: "MGA", name: "Malagasy Ariary (MGA)" },
  { code: "MKD", name: "Macedonian Denar (MKD)" },
  { code: "MMK", name: "Myanmar Kyat (MMK)" },
  { code: "MNT", name: "Mongolian Tugrik (MNT)" },
  { code: "MOP", name: "Macanese Pataca (MOP)" },
  { code: "MRU", name: "Mauritanian Ouguiya (MRU)" },
  { code: "MUR", name: "Mauritian Rupee (MUR)" },
  { code: "MVR", name: "Maldivian Rufiyaa (MVR)" },
  { code: "MWK", name: "Malawian Kwacha (MWK)" },
  { code: "MXN", name: "Mexican Peso (MXN)" },
  { code: "MYR", name: "Malaysian Ringgit (MYR)" },
  { code: "MZN", name: "Mozambican Metical (MZN)" },
  { code: "NAD", name: "Namibian Dollar (NAD)" },
  { code: "NGN", name: "Nigerian Naira (NGN)" },
  { code: "NIO", name: "Nicaraguan Córdoba (NIO)" },
  { code: "NOK", name: "Norwegian Krone (NOK)" },
  { code: "NPR", name: "Nepalese Rupee (NPR)" },
  { code: "NZD", name: "New Zealand Dollar (NZD)" },
  { code: "OMR", name: "Omani Rial (OMR)" },
  { code: "PAB", name: "Panamanian Balboa (PAB)" },
  { code: "PEN", name: "Peruvian Nuevo Sol (PEN)" },
  { code: "PGK", name: "Papua New Guinean Kina (PGK)" },
  { code: "PHP", name: "Philippine Peso (PHP)" },
  { code: "PKR", name: "Pakistani Rupee (PKR)" },
  { code: "PLN", name: "Polish Złoty (PLN)" },
  { code: "PYG", name: "Paraguayan Guarani (PYG)" },
  { code: "QAR", name: "Qatari Riyal (QAR)" },
  { code: "RON", name: "Romanian Leu (RON)" },
  { code: "RSD", name: "Serbian Dinar (RSD)" },
  { code: "RUB", name: "Russian Ruble (RUB)" },
  { code: "RWF", name: "Rwandan Franc (RWF)" },
  { code: "SAR", name: "Saudi Riyal (SAR)" },
  { code: "SBD", name: "Solomon Islands Dollar (SBD)" },
  { code: "SCR", name: "Seychellois Rupee (SCR)" },
  { code: "SDG", name: "Sudanese Pound (SDG)" },
  { code: "SEK", name: "Swedish Krona (SEK)" },
  { code: "SGD", name: "Singapore Dollar (SGD)" },
  { code: "SHP", name: "Saint Helena Pound (SHP)" },
  { code: "SLE", name: "Sierra Leonean Leone (SLE)" },
  { code: "SLL", name: "Sierra Leonean Leone (SLL)" },
  { code: "SOS", name: "Somali Shilling (SOS)" },
  { code: "SRD", name: "Surinamese Dollar (SRD)" },
  { code: "SSP", name: "South Sudanese Pound (SSP)" },
  { code: "STN", name: "São Tomé and Príncipe Dobra (STN)" },
  { code: "SYP", name: "Syrian Pound (SYP)" },
  { code: "SZL", name: "Swazi Lilangeni (SZL)" },
  { code: "THB", name: "Thai Baht (THB)" },
  { code: "TJS", name: "Tajikistani Somoni (TJS)" },
  { code: "TMT", name: "Turkmenistan Manat (TMT)" },
  { code: "TND", name: "Tunisian Dinar (TND)" },
  { code: "TOP", name: "Tongan Paanga (TOP)" },
  { code: "TRY", name: "Turkish Lira (TRY)" },
  { code: "TTD", name: "Trinidad and Tobago Dollar (TTD)" },
  { code: "TVD", name: "Tuvaluan Dollar (TVD)" },
  { code: "TWD", name: "New Taiwan Dollar (TWD)" },
  { code: "TZS", name: "Tanzanian Shilling (TZS)" },
  { code: "UAH", name: "Ukrainian Hryvnia (UAH)" },
  { code: "UGX", name: "Ugandan Shilling (UGX)" },
  { code: "USD", name: "United States Dollar (USD)" },
  { code: "UYU", name: "Uruguayan Peso (UYU)" },
  { code: "UZS", name: "Uzbekistan Som (UZS)" },
  { code: "VES", name: "Venezuelan Bolívar (VES)" },
  { code: "VND", name: "Vietnamese Đồng (VND)" },
  { code: "VUV", name: "Vanuatu Vatu (VUV)" },
  { code: "WST", name: "Samoan Tala (WST)" },
  { code: "XAF", name: "Central African CFA Franc (XAF)" },
  { code: "XCD", name: "East Caribbean Dollar (XCD)" },
  { code: "XDR", name: "Special Drawing Rights (XDR)" },
  { code: "XOF", name: "West African CFA Franc (XOF)" },
  { code: "XPF", name: "CFP Franc (XPF)" },
  { code: "YER", name: "Yemeni Rial (YER)" },
  { code: "ZAR", name: "South African Rand (ZAR)" },
  { code: "ZMW", name: "Zambian Kwacha (ZMW)" },
  { code: "ZWL", name: "Zimbabwean Dollar (ZWL)" },
];